### ISSUE TITLE
关于ide下载

### ISSUE THREAD

**Issue by warmonipa** [coder163/DelphiSource#1]
hi 老侯，感谢你对delphi普及的贡献，当前遇到一个问题，
从http://www.coder163.com/下载ide的时候到99.99%提示输入用户名密码，
这个问题怎么解，谢谢。

**Comment by coder163** [comment]
不好意思，今天才看到邮件，我最近会整合一下资源，我推荐你还是从官网下载，微软提供的网盘下载并不稳定

在 2019-10-20 17:13:41，"wangzhen" <notifications@github.com> 写道：


hi 老侯，感谢你对delphi普及的贡献，当前遇到一个问题，
从http://www.coder163.com/下载ide的时候到99.99%提示输入用户名密码，
这个问题怎么解，谢谢。

**Comment by warmonipa** [comment]
ok thx
